name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Action pour récupérer le code
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Installer les dépendances
        run: npm ci
      - name: Build
        run: npm run build  # Assurez-vous que ce script existe

  test:
    runs-on: ubuntu-latest
    needs: build  # Le job 'test' attend que 'build' soit terminé
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Installer les dépendances
        run: npm ci
      - name: Lancer les tests
        run: npm test